
backend:
  name: git-gateway
  branch: dev
site_url: "https://codesign-kit.netlify.app"
media_folder: "src/assets/images"
public_folder: "/assets/images"
collections:
  - name: pages
    label: Pages
    label_singular: Page
    folder: "src/pages"
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    create: true
    fields:
      - label: "Layout"
        name: "layout"
        widget: "select"
        default: "layouts/page"
        options:
          - { label: "Home", value: "layouts/home" }
          - { label: "Page", value: "layouts/page" }
          - { label: "Resources", value: "layouts/resources" }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
